"""add comment

Revision ID: 30dbe9b48386
Revises: dad567f47e25
Create Date: 2025-12-17 13:47:17.785733

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30dbe9b48386"
down_revision: Union[str, Sequence[str], None] = "dad567f47e25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("authorId", sa.Integer(), nullable=False),
        sa.Column("postId", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(
            ["authorId"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["postId"],
            ["posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_authorId"), "comments", ["authorId"], unique=False)
    op.create_index(op.f("ix_comments_postId"), "comments", ["postId"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_postId"), table_name="comments")
    op.drop_index(op.f("ix_comments_authorId"), table_name="comments")
    op.drop_table("comments")
    # ### end Alembic commands ###
