"""add saved post

Revision ID: 75c45e8d84be
Revises: 30dbe9b48386
Create Date: 2025-12-17 16:44:36.594206

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75c45e8d84be"
down_revision: Union[str, Sequence[str], None] = "30dbe9b48386"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_posts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("postId", sa.Integer(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(
            ["postId"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saved_posts_postId"), "saved_posts", ["postId"], unique=False)
    op.create_index(op.f("ix_saved_posts_userId"), "saved_posts", ["userId"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saved_posts_userId"), table_name="saved_posts")
    op.drop_index(op.f("ix_saved_posts_postId"), table_name="saved_posts")
    op.drop_table("saved_posts")
    # ### end Alembic commands ###
