"""add subscribes

Revision ID: b364c310aeb2
Revises: 75c45e8d84be
Create Date: 2025-12-17 16:45:50.313345

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b364c310aeb2"
down_revision: Union[str, Sequence[str], None] = "75c45e8d84be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscribes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("authorId", sa.Integer(), nullable=False),
        sa.Column("subscriberId", sa.Integer(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(
            ["authorId"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscriberId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscribes_authorId"), "subscribes", ["authorId"], unique=False)
    op.create_index(op.f("ix_subscribes_subscriberId"), "subscribes", ["subscriberId"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscribes_subscriberId"), table_name="subscribes")
    op.drop_index(op.f("ix_subscribes_authorId"), table_name="subscribes")
    op.drop_table("subscribes")
    # ### end Alembic commands ###
