"""category

Revision ID: dad567f47e25
Revises: cde2df35f8a9
Create Date: 2025-12-17 12:15:47.662075

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dad567f47e25"
down_revision: Union[str, Sequence[str], None] = "cde2df35f8a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "post_to_category",
        sa.Column("categoryId", sa.Integer(), nullable=False),
        sa.Column("postId", sa.Integer(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(
            ["categoryId"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["postId"],
            ["posts.id"],
        ),
        sa.PrimaryKeyConstraint("categoryId", "postId"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_to_category")
    op.drop_table("categories")
    # ### end Alembic commands ###
